create table if not exists public.conciliacoes (
  id bigint generated by default as identity primary key,
  usuario text not null,
  perfil text not null,
  empresa text,
  arquivo_omie text,
  arquivo_pref text,
  total_nfes integer,
  conciliadas integer,
  divergencia_valor integer,
  ausente_prefeitura integer,
  ausente_omie integer,
  criado_em timestamptz default now()
);

create table if not exists public.conciliacao_itens (
  id bigint generated by default as identity primary key,
  conciliacao_id bigint references public.conciliacoes(id) on delete cascade,
  nfe text,
  nome_omie text,
  nome_pref text,
  valor_omie numeric(18,2),
  valor_pref numeric(18,2),
  dif_valor numeric(18,2),
  status text,
  empresa text,
  criado_em timestamptz default now()
);